//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmDetails
    {
        public int ID_Details { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Address { get; set; }
        public string BankDetails { get; set; }
        public string Phone { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    }
}
