//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ID_OrderDetails { get; set; }
        public int ID_Order { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Price { get; set; }
        public int Count { get; set; }
        public System.DateTime PositionDateEnd { get; set; }
        public decimal PricePosition { get; set; }
        public decimal PriceDiscount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Price Price { get; set; }
    }
}
